### ISSUE TITLE
PyTTI-Tools: FiLM.ipynb Error

### ISSUE THREAD

**Issue by poppygavin** [pytti-tools/pytti-notebook#38]
Mounted at /content/drive/
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

-----[PYTTI-TOOLS]-------

If you received a scary OSError and your drive was already mounted, ignore it.

-----[PYTTI-TOOLS]-------

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-542bfb5a635d>", line 36, in <module>
    get_ipython().magic('cd {gdrive_fpath}')
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2160, in magic
    return self.run_line_magic(magic_name, magic_arg_s)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2081, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-84>", line 2, in cd
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/magic.py", line 188, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/magics/osm.py", line 288, in cd
    oldcwd = py3compat.getcwd()
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 1823, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'OSError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py", line 1132, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py", line 313, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py", line 358, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.7/inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.7/inspect.py", line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.7/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.7/inspect.py", line 725, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/lib/python3.7/inspect.py", line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/usr/lib/python3.7/posixpath.py", line 383, in abspath
    cwd = os.getcwd()
OSError: [Errno 107] Transport endpoint is not connected
---------------------------------------------------------------------------

**Comment by dmarx** [comment]
fascinating. try a reloading the page and doing a factory reset. lemme know if the error still shows up. 

also: what are the different settings and stuff you have set? like, are you trying to mount google drive? did you change any settings from the defaults?

**Comment by poppygavin** [comment]
Hey, David, thank you for getting back to me. I removed the original files
from my drive and reset everything, and this time the first cell went
through the mounting process, but it's not interpolating for some reason. I
put my frames in the folder as so, and it detects the amount, but it just
doesn't make the video or any of the process images. I haven't changed any
of the default settings either; also, do all frames need to be in the same
aspect ratio? I know some other models like that, and it will make sense
why it's not interpolating if that's the case. Thanks again for your help!

**Comment by dmarx** [comment]
> also, do all frames need to be in the same aspect ratio?

wait what? tell me more about this. you're trying to animate a sequence of frames that aren't all the same aspect ratio? what's your expected behavior here? It sounds like you're describing an interesting edge case that I've never considered and I want to be able to reproduce it.

thanks!
